### PR TITLE
[No JIRA] Handle promise rejection explicitly

### PR DESCRIPTION
**Pull request by k0nserv**

### CODE REVIEW

**Review by matthewdavidson — DISMISSED** [review]
LGTM

**Comment by matthewdavidson** [comment]
Hey @k0nserv, I changed the implementation of this to use the catch clause of the promise object returned from the top level async function as opposed to wrapping a try/catch around the code in question. What do you think?

**Comment by k0nserv** [comment]
Doesn't try/catch fit semantically better with the async/await keywords? The fact the promises are the underlying implementation is nicely hidden by that

**Comment by shaundon** [comment]
> Doesn't try/catch fit semantically better with the async/await keywords? 

That was my understanding too fwiw

**Comment by matthewdavidson** [comment]
Closing for now as this has stagnated.

**Pull request closed without merging**
